name: Build and Release Zygisk Dump Dex

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-linux-android
          override: true

      - name: Install Build Tools
        run: |
          cargo install just
          cargo install cargo-ndk

      - name: Build project
        run: just package-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-build-output
          path: out/zygisk-*.zip
          compression-level: 9

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code  # 新增代码检出步骤
        uses: actions/checkout@v4

      - name: Get Cargo Version
        id: cargo-version
        run: |
          # 添加调试输出
          echo "Current directory: $(pwd)"
          ls -la
          # 提取版本号
          VERSION=$(grep 'version =' Cargo.toml | head -1 | cut -d '"' -f 2)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT


      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: zygisk-build-output
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.cargo-version.outputs.VERSION }}"
          name: "Zygisk Dump Dex ${{ steps.cargo-version.outputs.VERSION }}"
          files: release-artifacts/*.zip
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(steps.cargo-version.outputs.VERSION, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
